name: Build

on:
  push:
    branches:
      - '*'
      - '!main' 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go version
      - run: go build -o out/generator .
      - run: go test -race -v ./...
      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc #v3
        with:
          version: v1.55.1
